/* eslint-disable no-unused-vars */
// !!! IMPORTANT: This file is autogenerated. Please do not edit.!!!
import WebpackerReact from 'webpacker-react'

// KIT EXAMPLES
import 'kits/pb_form/pb_form_validation'
import * as AdvancedTable from 'kits/pb_advanced_table/docs'
import * as Avatar from 'kits/pb_avatar/docs'
import * as Background from 'kits/pb_background/docs'
import * as Badge from 'kits/pb_badge/docs'
import * as BarGraphDocs from 'kits/pb_bar_graph/docs'
import * as Body from 'kits/pb_body/docs'
import * as BreadCrumbs from 'kits/pb_bread_crumbs/docs'
import * as Button from 'kits/pb_button/docs'
import * as ButtonToolbar from 'kits/pb_button_toolbar/docs'
import * as Caption from 'kits/pb_caption/docs'
import * as Card from 'kits/pb_card/docs'
import * as Checkbox from 'kits/pb_checkbox/docs'
import * as CircleChart from 'kits/pb_circle_chart/docs'
import * as CircleIconButton from 'kits/pb_circle_icon_button/docs'
import * as Collapsible from 'kits/pb_collapsible/docs'
import * as Contact from 'kits/pb_contact/docs'
import * as CopyButton from 'kits/pb_copy_button/docs'
import * as Currency from 'kits/pb_currency/docs'
import * as DashboardValue from 'kits/pb_dashboard_value/docs'
import * as Date from 'kits/pb_date/docs'
import * as DatePicker from 'kits/pb_date_picker/docs'
import * as DateRangeInline from 'kits/pb_date_range_inline/docs'
import * as DateRangeStacked from 'kits/pb_date_range_stacked/docs'
import * as DateStacked from 'kits/pb_date_stacked/docs'
import * as DateTime from 'kits/pb_date_time/docs'
import * as DateTimeStacked from 'kits/pb_date_time_stacked/docs'
import * as DateYearStacked from 'kits/pb_date_year_stacked/docs'
import * as Detail from 'kits/pb_detail/docs'
import * as Dialog from 'kits/pb_dialog/docs'
import * as DistributionBarDocs from 'kits/pb_distribution_bar/docs'
import * as Draggable from 'kits/pb_draggable/docs'
import * as Dropdown from 'kits/pb_dropdown/docs'
import * as EmptyState from 'kits/pb_empty_state/docs'
import * as FileUpload from 'kits/pb_file_upload/docs'
import * as Filter from 'kits/pb_filter/docs'
import * as FixedConfirmationToast from 'kits/pb_fixed_confirmation_toast/docs'
import * as Flex from 'kits/pb_flex/docs'
import * as FormGroup from 'kits/pb_form_group/docs'
import * as FormPill from 'kits/pb_form_pill/docs'
import * as Gauge from 'kits/pb_gauge/docs'
import * as Hashtag from 'kits/pb_hashtag/docs'
import * as Highlight from 'kits/pb_highlight/docs'
import * as HomeAddressStreet from 'kits/pb_home_address_street/docs'
import * as Icon from 'kits/pb_icon/docs'
import * as IconButton from 'kits/pb_icon_button/docs'
import * as IconCircle from 'kits/pb_icon_circle/docs'
import * as IconStatValue from 'kits/pb_icon_stat_value/docs'
import * as IconValue from 'kits/pb_icon_value/docs'
import * as Image from 'kits/pb_image/docs'
import * as LabelPill from 'kits/pb_label_pill/docs'
import * as LabelValue from 'kits/pb_label_value/docs'
import * as Layout from 'kits/pb_layout/docs'
import * as LegendDocs from 'kits/pb_legend/docs'
import * as Lightbox from 'kits/pb_lightbox/docs'
import * as LineGraphDocs from 'kits/pb_line_graph/docs'
import * as Link from 'kits/pb_link/docs'
import * as List from 'kits/pb_list/docs'
import * as LoadingInline from 'kits/pb_loading_inline/docs'
import * as Map from 'kits/pb_map/docs'
import * as Message from 'kits/pb_message/docs'
import * as MultiLevelSelect from 'kits/pb_multi_level_select/docs'
import * as MultipleUsers from 'kits/pb_multiple_users/docs'
import * as MultipleUsersStacked from 'kits/pb_multiple_users_stacked/docs'
import * as Nav from 'kits/pb_nav/docs'
import * as OnlineStatus from 'kits/pb_online_status/docs'
import * as Overlay from 'kits/pb_overlay/docs'
import * as Pagination from 'kits/pb_pagination/docs'
import * as Passphrase from 'kits/pb_passphrase/docs'
import * as PbReactPopover from 'kits/pb_popover/docs'
import * as Person from 'kits/pb_person/docs'
import * as PersonContact from 'kits/pb_person_contact/docs'
import * as PhoneNumberInput from 'kits/pb_phone_number_input/docs'
import * as Pill from 'kits/pb_pill/docs'
import * as ProgressPills from 'kits/pb_progress_pills/docs'
import * as ProgressSimple from 'kits/pb_progress_simple/docs'
import * as ProgressStep from 'kits/pb_progress_step/docs'
import * as Radio from 'kits/pb_radio/docs'
import * as RichTextEditor from 'kits/pb_rich_text_editor/docs'
import * as SectionSeparator from 'kits/pb_section_separator/docs'
import * as Select from 'kits/pb_select/docs'
import * as SelectableCard from 'kits/pb_selectable_card/docs'
import * as SelectableCardIcon from 'kits/pb_selectable_card_icon/docs'
import * as SelectableIcon from 'kits/pb_selectable_icon/docs'
import * as SelectableList from 'kits/pb_selectable_list/docs'
import * as SkeletonLoading from 'kits/pb_skeleton_loading/docs'
import * as Source from 'kits/pb_source/docs'
import * as StarRating from 'kits/pb_star_rating/docs'
import * as StatChange from 'kits/pb_stat_change/docs'
import * as StatValue from 'kits/pb_stat_value/docs'
import * as Table from 'kits/pb_table/docs'
import * as TextInput from 'kits/pb_text_input/docs'
import * as Textarea from 'kits/pb_textarea/docs'
import * as Time from 'kits/pb_time/docs'
import * as TimeRangeInline from 'kits/pb_time_range_inline/docs'
import * as TimeStacked from 'kits/pb_time_stacked/docs'
import * as Timeline from 'kits/pb_timeline/docs'
import * as Timestamp from 'kits/pb_timestamp/docs'
import * as Title from 'kits/pb_title/docs'
import * as TitleCount from 'kits/pb_title_count/docs'
import * as TitleDetail from 'kits/pb_title_detail/docs'
import * as Toggle from 'kits/pb_toggle/docs'
import * as Tooltip from 'kits/pb_tooltip/docs'
import * as Typeahead from 'kits/pb_typeahead/docs'
import * as User from 'kits/pb_user/docs'
import * as UserBadge from 'kits/pb_user_badge/docs'
import * as WeekdayStacked from 'kits/pb_weekday_stacked/docs'

WebpackerReact.registerComponents({
  ...AdvancedTable,
  ...Avatar,
  ...Background,
  ...Badge,
  ...BarGraphDocs,
  ...Body,
  ...BreadCrumbs,
  ...Button,
  ...ButtonToolbar,
  ...Caption,
  ...Card,
  ...Checkbox,
  ...CircleChart,
  ...CircleIconButton,
  ...Collapsible,
  ...Contact,
  ...CopyButton,
  ...Currency,
  ...DashboardValue,
  ...Date,
  ...DatePicker,
  ...DateRangeInline,
  ...DateRangeStacked,
  ...DateStacked,
  ...DateTime,
  ...DateTimeStacked,
  ...DateYearStacked,
  ...Detail,
  ...Dialog,
  ...DistributionBarDocs,
  ...Draggable,
  ...Dropdown,
  ...EmptyState,
  ...FileUpload,
  ...Filter,
  ...FixedConfirmationToast,
  ...Flex,
  ...FormGroup,
  ...FormPill,
  ...Gauge,
  ...Hashtag,
  ...Highlight,
  ...HomeAddressStreet,
  ...Icon,
  ...IconButton,
  ...IconCircle,
  ...IconStatValue,
  ...IconValue,
  ...Image,
  ...LabelPill,
  ...LabelValue,
  ...Layout,
  ...LegendDocs,
  ...Lightbox,
  ...LineGraphDocs,
  ...Link,
  ...List,
  ...LoadingInline,
  ...Map,
  ...Message,
  ...MultiLevelSelect,
  ...MultipleUsers,
  ...MultipleUsersStacked,
  ...Nav,
  ...OnlineStatus,
  ...Overlay,
  ...Pagination,
  ...Passphrase,
  ...PbReactPopover,
  ...Person,
  ...PersonContact,
  ...PhoneNumberInput,
  ...Pill,
  ...ProgressPills,
  ...ProgressSimple,
  ...ProgressStep,
  ...Radio,
  ...RichTextEditor,
  ...SectionSeparator,
  ...Select,
  ...SelectableCard,
  ...SelectableCardIcon,
  ...SelectableIcon,
  ...SelectableList,
  ...SkeletonLoading,
  ...Source,
  ...StarRating,
  ...StatChange,
  ...StatValue,
  ...Table,
  ...TextInput,
  ...Textarea,
  ...Time,
  ...TimeRangeInline,
  ...TimeStacked,
  ...Timeline,
  ...Timestamp,
  ...Title,
  ...TitleCount,
  ...TitleDetail,
  ...Toggle,
  ...Tooltip,
  ...Typeahead,
  ...User,
  ...UserBadge,
  ...WeekdayStacked,
})
