examples:
  
  rails:
  - loading_inline_default: Default
  - loading_inline_custom: Custom Text
  - loading_inline_variant: Variant
  - loading_inline_color: Color

  
  
  react:
  - loading_inline_default: Default
  - loading_inline_custom: Custom Text
  - loading_inline_variant: Variant
  - loading_inline_color: Color
