# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.0"

gem "playbook_ui", path: "../playbook"

gem "rails", "~> 7.0.8"
gem "turbo-rails", "~> 1.4.0"
gem "puma", "~> 6.3"
gem "webpacker", "5.4.4"
# Make Compatible with Ruby 3.1.0 Upgrade
gem "psych", "< 4"
gem "bootsnap", ">= 1.1.0", require: false

# livenessProbe and readinessProbe. See: https://github.com/powerhome/playbook/blob/master/playbook/config/deploy/templates/deployment.yaml.erb
gem "health_check"

gem "redcarpet", "~> 3.6"
gem 'front_matter_parser', "~> 1.0.1"
gem "rouge", "~> 3.15"
gem "faker"
gem "will_paginate"
gem "sentry-ruby"
gem "sentry-rails"
gem "sanitize"
gem 'brakeman'
gem 'overcommit'
gem 'erb_lint'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem "listen"
  gem "rubocop"
  gem "rubocop-performance"
  gem "web-console"
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem "capybara", ">= 2.15"
  gem "selenium-webdriver"
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem "chromedriver-helper"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data"
