/* eslint-disable no-unused-vars */
// !!! IMPORTANT: This file is autogenerated. Please do not edit.!!!
import WebpackerReact from 'webpacker-react'

// KIT EXAMPLES
import 'pb_form/pb_form_validation'
import * as AdvancedTable from 'pb_advanced_table/docs'
import * as Avatar from 'pb_avatar/docs'
import * as AvatarActionButton from 'pb_avatar_action_button/docs'
import * as Background from 'pb_background/docs'
import * as Badge from 'pb_badge/docs'
import * as BarGraphDocs from 'pb_bar_graph/docs'
import * as Body from 'pb_body/docs'
import * as BreadCrumbs from 'pb_bread_crumbs/docs'
import * as Button from 'pb_button/docs'
import * as ButtonToolbar from 'pb_button_toolbar/docs'
import * as Caption from 'pb_caption/docs'
import * as Card from 'pb_card/docs'
import * as Checkbox from 'pb_checkbox/docs'
import * as CircleChart from 'pb_circle_chart/docs'
import * as CircleIconButton from 'pb_circle_icon_button/docs'
import * as Collapsible from 'pb_collapsible/docs'
import * as Contact from 'pb_contact/docs'
import * as Currency from 'pb_currency/docs'
import * as DashboardValue from 'pb_dashboard_value/docs'
import * as Date from 'pb_date/docs'
import * as DatePicker from 'pb_date_picker/docs'
import * as DateRangeInline from 'pb_date_range_inline/docs'
import * as DateRangeStacked from 'pb_date_range_stacked/docs'
import * as DateStacked from 'pb_date_stacked/docs'
import * as DateTime from 'pb_date_time/docs'
import * as DateTimeStacked from 'pb_date_time_stacked/docs'
import * as DateYearStacked from 'pb_date_year_stacked/docs'
import * as Detail from 'pb_detail/docs'
import * as Dialog from 'pb_dialog/docs'
import * as DistributionBarDocs from 'pb_distribution_bar/docs'
import * as Dropdown from 'pb_dropdown/docs'
import * as FileUpload from 'pb_file_upload/docs'
import * as Filter from 'pb_filter/docs'
import * as FixedConfirmationToast from 'pb_fixed_confirmation_toast/docs'
import * as Flex from 'pb_flex/docs'
import * as FormGroup from 'pb_form_group/docs'
import * as FormPill from 'pb_form_pill/docs'
import * as Gauge from 'pb_gauge/docs'
import * as GradientOverlay from 'pb_gradient_overlay/docs'
import * as Hashtag from 'pb_hashtag/docs'
import * as Highlight from 'pb_highlight/docs'
import * as HomeAddressStreet from 'pb_home_address_street/docs'
import * as Icon from 'pb_icon/docs'
import * as IconCircle from 'pb_icon_circle/docs'
import * as IconStatValue from 'pb_icon_stat_value/docs'
import * as IconValue from 'pb_icon_value/docs'
import * as Image from 'pb_image/docs'
import * as LabelPill from 'pb_label_pill/docs'
import * as LabelValue from 'pb_label_value/docs'
import * as Layout from 'pb_layout/docs'
import * as LegendDocs from 'pb_legend/docs'
import * as Lightbox from 'pb_lightbox/docs'
import * as LineGraphDocs from 'pb_line_graph/docs'
import * as List from 'pb_list/docs'
import * as LoadingInline from 'pb_loading_inline/docs'
import * as Map from 'pb_map/docs'
import * as Message from 'pb_message/docs'
import * as MultiLevelSelect from 'pb_multi_level_select/docs'
import * as MultipleUsers from 'pb_multiple_users/docs'
import * as MultipleUsersStacked from 'pb_multiple_users_stacked/docs'
import * as Nav from 'pb_nav/docs'
import * as OnlineStatus from 'pb_online_status/docs'
import * as Passphrase from 'pb_passphrase/docs'
import * as PbReactPopover from 'pb_popover/docs'
import * as Person from 'pb_person/docs'
import * as PersonContact from 'pb_person_contact/docs'
import * as PhoneNumberInput from 'pb_phone_number_input/docs'
import * as Pill from 'pb_pill/docs'
import * as ProgressPills from 'pb_progress_pills/docs'
import * as ProgressSimple from 'pb_progress_simple/docs'
import * as ProgressStep from 'pb_progress_step/docs'
import * as Radio from 'pb_radio/docs'
import * as RichTextEditor from 'pb_rich_text_editor/docs'
import * as SectionSeparator from 'pb_section_separator/docs'
import * as Select from 'pb_select/docs'
import * as SelectableCard from 'pb_selectable_card/docs'
import * as SelectableCardIcon from 'pb_selectable_card_icon/docs'
import * as SelectableIcon from 'pb_selectable_icon/docs'
import * as SelectableList from 'pb_selectable_list/docs'
import * as Source from 'pb_source/docs'
import * as StarRating from 'pb_star_rating/docs'
import * as StatChange from 'pb_stat_change/docs'
import * as StatValue from 'pb_stat_value/docs'
import * as Table from 'pb_table/docs'
import * as TextInput from 'pb_text_input/docs'
import * as Textarea from 'pb_textarea/docs'
import * as Time from 'pb_time/docs'
import * as TimeRangeInline from 'pb_time_range_inline/docs'
import * as TimeStacked from 'pb_time_stacked/docs'
import * as Timeline from 'pb_timeline/docs'
import * as Timestamp from 'pb_timestamp/docs'
import * as Title from 'pb_title/docs'
import * as TitleCount from 'pb_title_count/docs'
import * as TitleDetail from 'pb_title_detail/docs'
import * as Toggle from 'pb_toggle/docs'
import * as Tooltip from 'pb_tooltip/docs'
import * as TreemapChart from 'pb_treemap_chart/docs'
import * as Typeahead from 'pb_typeahead/docs'
import * as User from 'pb_user/docs'
import * as UserBadge from 'pb_user_badge/docs'
import * as Walkthrough from 'pb_walkthrough/docs'
import * as WeekdayStacked from 'pb_weekday_stacked/docs'

WebpackerReact.registerComponents({
  ...AdvancedTable,
  ...Avatar,
  ...AvatarActionButton,
  ...Background,
  ...Badge,
  ...BarGraphDocs,
  ...Body,
  ...BreadCrumbs,
  ...Button,
  ...ButtonToolbar,
  ...Caption,
  ...Card,
  ...Checkbox,
  ...CircleChart,
  ...CircleIconButton,
  ...Collapsible,
  ...Contact,
  ...Currency,
  ...DashboardValue,
  ...Date,
  ...DatePicker,
  ...DateRangeInline,
  ...DateRangeStacked,
  ...DateStacked,
  ...DateTime,
  ...DateTimeStacked,
  ...DateYearStacked,
  ...Detail,
  ...Dialog,
  ...DistributionBarDocs,
  ...Dropdown,
  ...FileUpload,
  ...Filter,
  ...FixedConfirmationToast,
  ...Flex,
  ...FormGroup,
  ...FormPill,
  ...Gauge,
  ...GradientOverlay,
  ...Hashtag,
  ...Highlight,
  ...HomeAddressStreet,
  ...Icon,
  ...IconCircle,
  ...IconStatValue,
  ...IconValue,
  ...Image,
  ...LabelPill,
  ...LabelValue,
  ...Layout,
  ...LegendDocs,
  ...Lightbox,
  ...LineGraphDocs,
  ...List,
  ...LoadingInline,
  ...Map,
  ...Message,
  ...MultiLevelSelect,
  ...MultipleUsers,
  ...MultipleUsersStacked,
  ...Nav,
  ...OnlineStatus,
  ...Passphrase,
  ...PbReactPopover,
  ...Person,
  ...PersonContact,
  ...PhoneNumberInput,
  ...Pill,
  ...ProgressPills,
  ...ProgressSimple,
  ...ProgressStep,
  ...Radio,
  ...RichTextEditor,
  ...SectionSeparator,
  ...Select,
  ...SelectableCard,
  ...SelectableCardIcon,
  ...SelectableIcon,
  ...SelectableList,
  ...Source,
  ...StarRating,
  ...StatChange,
  ...StatValue,
  ...Table,
  ...TextInput,
  ...Textarea,
  ...Time,
  ...TimeRangeInline,
  ...TimeStacked,
  ...Timeline,
  ...Timestamp,
  ...Title,
  ...TitleCount,
  ...TitleDetail,
  ...Toggle,
  ...Tooltip,
  ...TreemapChart,
  ...Typeahead,
  ...User,
  ...UserBadge,
  ...Walkthrough,
  ...WeekdayStacked,
})
