examples:
  
  rails:
  - full_screen_default: Default
  
  
  react:
  - full_screen_default: Default
  - full_screen_custom_trigger: Custom Trigger
  - full_screen_header_text_styling: Header Text Styling
  - full_screen_sticky_header: Sticky Header
  - full_screen_content_padding: Content Padding
  - full_screen_table_and_filter: Complex Example
  
