examples:
  
  rails:
  - container_default: Default
  - container_tag: Tag
  - container_global_props: Global Props
  
  
  react:
  - container_default: Default
  - container_tag: Tag
  - container_global_props: Global Props
