export type BackgroundColors = "white" | "dark" | "light"
export type CategoryColors = "category_1" | "category_2" | "category_3" | "category_4" | "category_5" | "category_6" | "category_7" | "category_8" | "category_9" | "category_10" | "category_11" | "category_12" | "category_13" | "category_14" | "category_15" | "category_16" | "category_17" | "category_18" | "category_19" | "category_20" | "category_21"
export type ProductColors = "windows" | "siding" | "doors" | "solar" | "roofing" | "gutters" | "insulation"
export type TextColors = "text_lt_default" | "text_lt_light" | "text_lt_lighter" | "text_dk_default" | "text_dk_default" | "text_dk_default"
export type CardColors = "card_light" | "card_dark"
export type StatusColors = "success" | "warning" | "error" | "info" | "neutral"
export type DataColors = "data_1" | "data_2" | "data_3" | "data_4" | "data_5" | "data_6" | "data_7" | "data_8"
export type BorderColors = "border_light" | "border_dark"
